version: '2'
services:
  softether-vpnclient:
    image: oriolrius/softether-vpnclient
    container_name: softether-vpnclient
    privileged: true
    network_mode: host
    restart: unless-stopped
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
      - ./config/vpn_client.config:/usr/local/libexec/softether/vpnclient/vpn_client.config
      - ./config/lang.config:/usr/local/libexec/softether/vpnclient/lang.config
      - ./log:/usr/local/libexec/softether/vpnclient/client_log
    build: .
      
